NewWebApp/NewWebApp/Controllers/NewEmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewWebApp.Data;
using NewWebApp.Models;
using NewWebApp.Models.Domain;

namespace NewWebApp.Controllers
{
    public class NewEmployeesController : Controller
    {
        private readonly MVCDemoDbContext mvcDemoDbContext;

        public NewEmployeesController(MVCDemoDbContext mvcDemoDbContext)
        {
            this.mvcDemoDbContext = mvcDemoDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var employees = await mvcDemoDbContext.NewEmployees.ToListAsync();
            return View(employees);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeViewModel addEmployeeRequest)
        {
            //var employee = new NewEmployee()
            //{
            //    Id = Guid.NewGuid(),
            //    Name = addEmployeeRequest.Name,
            //    Email = addEmployeeRequest.Email,
            //    Salary = addEmployeeRequest.Salary,
            //    Department = addEmployeeRequest.Department,
            //    DateOfBirth = addEmployeeRequest.DateOfBirth
            //};
            //await mvcDemoDbContext.NewEmployees.AddAsync(employee);
            //await mvcDemoDbContext.SaveChangesAsync();
            //return RedirectToAction("Add");

            var employee = new NewEmployee();
            await mvcDemoDbContext.Database.ExecuteSqlInterpolatedAsync($@"
            EXEC SP_Insert_NewEmployee 
            @Name = {addEmployeeRequest.Name},
            @Email = {addEmployeeRequest.Email},
            @Salary = {addEmployeeRequest.Salary},
            @DateOfBirth = {addEmployeeRequest.DateOfBirth},
            @Department = {addEmployeeRequest.Department}");

            await mvcDemoDbContext.NewEmployees.AddAsync(employee);
            await mvcDemoDbContext.SaveChangesAsync();

            return RedirectToAction("Index");

        }



    }
}

NewWebApp/NewWebApp/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewWebApp.Data;
using NewWebApp.Models;
using NewWebApp.Models.Domain;

namespace NewWebApp.Controllers
{
	public class TestController : Controller
	{
		private readonly MVCDemoDbContext mvcDemoDbContext;

		public TestController(MVCDemoDbContext mvcDemoDbContext)
		{
			this.mvcDemoDbContext = mvcDemoDbContext;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var test = await mvcDemoDbContext.Tests1.ToListAsync();
			return View(test);
		}

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTest addTest)
        {
            //var test = new Test1()
            //{
            //    FullName = addTest.FullName
            //};
            //await mvcDemoDbContext.Tests1.AddAsync(test);
            //await mvcDemoDbContext.SaveChangesAsync();
            //return RedirectToAction("Index");


            //var test = new Test1();
            await mvcDemoDbContext.Database.ExecuteSqlInterpolatedAsync($@"
            EXEC InsertTest1
            @FullName = {addTest.FullName}");

            //await mvcDemoDbContext.Tests1.AddAsync(test);
            //await mvcDemoDbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

NewWebApp/NewWebApp/Controllers/UserRatingController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NewWebApp.Data;
using NewWebApp.Models.Domain;
using NewWebApp.Models;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;
using AddUserRating = NewWebApp.Models.Domain.AddUserRating;

namespace NewWebApp.Controllers
{
    public class UserRatingController : Controller
    {
        private readonly MVCDemoDbContext mvcDemoDbContext;

        public UserRatingController(MVCDemoDbContext mvcDemoDbContext)
        {
            this.mvcDemoDbContext = mvcDemoDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userRatings = await mvcDemoDbContext.UserRatings.ToListAsync();
            return View(userRatings);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddUserRating userRating)
        {

            var userRating1 = new UserRating();

            //await mvcDemoDbContext.Database.ExecuteSqlInterpolatedAsync($@"
            //EXEC InsertTest1
            //@FullName = {userRating.FullName},
            //@Score = {userRating.Score},");

            await mvcDemoDbContext.Database.ExecuteSqlInterpolatedAsync($@"
            EXEC InsertUserRating
            @FullName = {userRating.FullName},
            @Score = {userRating.Score}
            ");

            return RedirectToAction("Index");

        }
    }
}

NewWebApp/NewWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NewWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NewWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FileList">FileList</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewEmployees" asp-action="Add">Add NewEmployees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewEmployees" asp-action="Index">NewEmployees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Add">Add Test1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserRating" asp-action="Index">UserRating</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserRating" asp-action="Add">UserRating</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Задании</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NewWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>